<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <UserSecretsId>b0cf97ef-1b9c-4130-af34-6c27066b075e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.10" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="HavaDurumuOrtak\HavaDurumuOrtak.csproj" />
  </ItemGroup>

  <!-- Diğer projeler bu projenin alt klasöründe yer aldığı için varsayılan glob'un
       onların dosyalarını da derlemeye dahil etmesini önlüyoruz -->
  <ItemGroup>
    <Compile Remove="HavaDurumuOrtak\**\*.cs" />
    <Compile Remove="HavaDurumuConsumer\**\*.cs" />
    <Content Remove="HavaDurumuOrtak\**\*" />
    <Content Remove="HavaDurumuConsumer\**\*" />
    <None Remove="HavaDurumuOrtak\**\*" />
    <None Remove="HavaDurumuConsumer\**\*" />
  </ItemGroup>

</Project>
